"""
Dati canonici dei privilegi di classe per D&D 5e (PHB).
Ogni entry: {"name": str, "level": int}
Basato su System Reference Document 5.1 (Creative Commons CC-BY-4.0).
"""

CLASS_FEATURES = {
    "barbaro": [
        {"name": "Ira", "level": 1},
        {"name": "Difesa Senza Armatura", "level": 1},
        {"name": "Attacco Irruento", "level": 2},
        {"name": "Percezione del Pericolo", "level": 2},
        {"name": "Cammino Primordiale", "level": 3},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Attacco Extra", "level": 5},
        {"name": "Movimento Veloce", "level": 5},
        {"name": "Istinto Ferino", "level": 7},
        {"name": "Mente Bestiale", "level": 10},
        {"name": "Critico Brutale", "level": 9},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Ira Implacabile", "level": 11},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Cammino Primordiale", "level": 6},
        {"name": "Privilegio del Cammino", "level": 14},
        {"name": "Ira Persistente", "level": 15},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Critico Brutale", "level": 17},
        {"name": "Potenza Indomabile", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
        {"name": "Campione Primordiale", "level": 20},
    ],
    "bardo": [
        {"name": "Incantesimi", "level": 1},
        {"name": "Ispirazione Bardica", "level": 1},
        {"name": "Tuttofare", "level": 2},
        {"name": "Canzone di Riposo", "level": 2},
        {"name": "Collegio Bardico", "level": 3},
        {"name": "Competenza Esperta", "level": 3},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Fonte di Ispirazione", "level": 5},
        {"name": "Contrincantesimo", "level": 6},
        {"name": "Competenze Bonus", "level": 6},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Segreti Magici", "level": 10},
        {"name": "Ispirazione Bardica (d10)", "level": 10},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Segreti Magici", "level": 14},
        {"name": "Ispirazione Bardica (d12)", "level": 15},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Segreti Magici", "level": 18},
        {"name": "Canzone di Riposo (d12)", "level": 17},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
        {"name": "Parole di Creazione", "level": 20},
    ],
    "chierico": [
        {"name": "Incantesimi", "level": 1},
        {"name": "Dominio Divino", "level": 1},
        {"name": "Privilegi del Dominio Divino", "level": 2},
        {"name": "Incanalare Divinità: Convertire i Non-Morti", "level": 2},
        {"name": "Incanalare Divinità", "level": 2},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Distruggi Non-Morti", "level": 5},
        {"name": "Privilegi del Dominio Divino", "level": 6},
        {"name": "Incanalare Divinità (2/riposo)", "level": 6},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Intervento Divino", "level": 10},
        {"name": "Incanalare Divinità (3/riposo)", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Distruggi Non-Morti (migliorato)", "level": 11},
        {"name": "Privilegio del Dominio Divino", "level": 17},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Intervento Divino (migliorato)", "level": 20},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
    ],
    "druido": [
        {"name": "Druidico", "level": 1},
        {"name": "Incantesimi", "level": 1},
        {"name": "Forma Selvatica", "level": 2},
        {"name": "Circolo Druidico", "level": 2},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Forma Selvatica (migliorata)", "level": 4},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Senso della Natura", "level": 10},
        {"name": "Forme Bestiali (migliorato)", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Druido Sempiterno", "level": 18},
        {"name": "Arcidruido", "level": 20},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
    ],
    "guerriero": [
        {"name": "Stile di Combattimento", "level": 1},
        {"name": "Secondo Fiato", "level": 1},
        {"name": "Azione Impetuosa", "level": 2},
        {"name": "Archetipo Marziale", "level": 3},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Attacco Extra", "level": 5},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 6},
        {"name": "Privilegio dell'Archetipo Marziale", "level": 7},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Indomabile", "level": 9},
        {"name": "Privilegio dell'Archetipo Marziale", "level": 10},
        {"name": "Attacco Extra (2)", "level": 11},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Indomabile (2 usi)", "level": 13},
        {"name": "Privilegio dell'Archetipo Marziale", "level": 15},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 14},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Attacco Extra (3)", "level": 20},
        {"name": "Indomabile (3 usi)", "level": 17},
        {"name": "Privilegio dell'Archetipo Marziale", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
    ],
    "monaco": [
        {"name": "Arti Marziali", "level": 1},
        {"name": "Difesa Senza Armatura", "level": 1},
        {"name": "Ki", "level": 2},
        {"name": "Movimento Senza Armatura", "level": 2},
        {"name": "Tradizione Monastica", "level": 3},
        {"name": "Deviare Proiettili", "level": 3},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Caduta Rallentata", "level": 4},
        {"name": "Attacco Extra", "level": 5},
        {"name": "Colpo Stordente", "level": 5},
        {"name": "Colpire il Ki", "level": 6},
        {"name": "Privilegio della Tradizione Monastica", "level": 6},
        {"name": "Elusione", "level": 7},
        {"name": "Quiete della Mente", "level": 7},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Immunità alle Malattie", "level": 10},
        {"name": "Privilegio della Tradizione Monastica", "level": 11},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Anima di Diamante", "level": 14},
        {"name": "Giovinezza Eterna", "level": 15},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Privilegio della Tradizione Monastica", "level": 17},
        {"name": "Corpo Vuoto", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
        {"name": "Perfezione dell'Io", "level": 20},
    ],
    "paladino": [
        {"name": "Rilevare il Male e il Bene", "level": 1},
        {"name": "Imposizione delle Mani", "level": 1},
        {"name": "Stile di Combattimento", "level": 2},
        {"name": "Incantesimi", "level": 2},
        {"name": "Folgore Divina", "level": 2},
        {"name": "Salute Divina", "level": 3},
        {"name": "Sacro Giuramento", "level": 3},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Attacco Extra", "level": 5},
        {"name": "Aura di Protezione", "level": 6},
        {"name": "Privilegi del Sacro Giuramento", "level": 7},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Aura di Coraggio", "level": 10},
        {"name": "Folgore Divina (migliorata)", "level": 11},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Salute Purificante", "level": 14},
        {"name": "Aura di Protezione (estesa)", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Privilegio del Sacro Giuramento", "level": 20},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
    ],
    "ranger": [
        {"name": "Nemico Prescelto", "level": 1},
        {"name": "Esploratore Naturale", "level": 1},
        {"name": "Stile di Combattimento", "level": 2},
        {"name": "Incantesimi", "level": 2},
        {"name": "Archetipo del Ranger", "level": 3},
        {"name": "Attenzione Primitiva", "level": 3},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Attacco Extra", "level": 5},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 6},
        {"name": "Privilegi dell'Archetipo del Ranger", "level": 7},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Scaltrezza Selvaggia", "level": 8},
        {"name": "Privilegi dell'Archetipo del Ranger", "level": 11},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Privilegi dell'Archetipo del Ranger", "level": 15},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 14},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Cacciatore Implacabile", "level": 20},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
    ],
    "ladro": [
        {"name": "Maestria", "level": 1},
        {"name": "Attacco Furtivo", "level": 1},
        {"name": "Gergo dei Ladri", "level": 1},
        {"name": "Azione Scaltra", "level": 2},
        {"name": "Archetipo Ladresco", "level": 3},
        {"name": "Schivata Prodigiosa", "level": 4},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Elusione", "level": 7},
        {"name": "Maestria (migliorata)", "level": 6},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Privilegio dell'Archetipo Ladresco", "level": 9},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 10},
        {"name": "Riflessi Affidabili", "level": 11},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Senso Cieco", "level": 14},
        {"name": "Mente Scivolosa", "level": 15},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Privilegio dell'Archetipo Ladresco", "level": 17},
        {"name": "Imprendibile", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
        {"name": "Colpo del Destino", "level": 20},
    ],
    "stregone": [
        {"name": "Origine Stregonesca", "level": 1},
        {"name": "Incantesimi", "level": 1},
        {"name": "Fonte di Magia", "level": 2},
        {"name": "Metamagia", "level": 3},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Privilegio dell'Origine Stregonesca", "level": 6},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Metamagia Aggiuntiva", "level": 10},
        {"name": "Privilegio dell'Origine Stregonesca", "level": 14},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Ripristino delle Stregonerie", "level": 20},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Metamagia Aggiuntiva", "level": 17},
        {"name": "Privilegio dell'Origine Stregonesca", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
    ],
    "warlock": [
        {"name": "Patrono Ultraterreno", "level": 1},
        {"name": "Incantesimi del Patto", "level": 1},
        {"name": "Doni del Patrono", "level": 2},
        {"name": "Invocazioni Eldritch", "level": 2},
        {"name": "Benedizione del Patto", "level": 3},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Invocazioni Eldritch Aggiuntive", "level": 5},
        {"name": "Privilegio del Patrono", "level": 6},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Privilegio del Patrono", "level": 10},
        {"name": "Magia Mistica", "level": 11},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Magia Mistica (grado 2)", "level": 13},
        {"name": "Privilegio del Patrono", "level": 14},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Magia Mistica (grado 3)", "level": 15},
        {"name": "Magia Mistica (grado 4)", "level": 17},
        {"name": "Privilegio del Patrono", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
        {"name": "Magia Mistica (grado 5)", "level": 19},
        {"name": "Evocatore Supremo", "level": 20},
    ],
    "mago": [
        {"name": "Incantesimi", "level": 1},
        {"name": "Recupero Arcano", "level": 1},
        {"name": "Tradizione Arcana", "level": 2},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Privilegio della Tradizione Arcana", "level": 6},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Privilegio della Tradizione Arcana", "level": 10},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Privilegio della Tradizione Arcana", "level": 14},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Padronanza degli Incantesimi", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
        {"name": "Firma degli Incantesimi", "level": 20},
    ],
    # ─── ARTEFICE (Tasha's Cauldron of Everything) ────────────────────────────
    "artefice": [
        {"name": "Lancio di Incantesimi Magici", "level": 1},
        {"name": "Competenza negli Strumenti", "level": 1},
        {"name": "Infusioni dell'Artefice", "level": 2},
        {"name": "Specialista Artefice", "level": 3},
        {"name": "Talento dell'Artefice", "level": 3},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 4},
        {"name": "Privilegio dello Specialista", "level": 5},
        {"name": "Esperto nello Strumento", "level": 6},
        {"name": "Talento dell'Artefice", "level": 7},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 8},
        {"name": "Privilegio dello Specialista", "level": 9},
        {"name": "Esperto Magico", "level": 10},
        {"name": "Modello del Distillatore di Pozioni", "level": 11},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 12},
        {"name": "Modello dello Stivali del Cammino", "level": 13},
        {"name": "Talento dell'Artefice", "level": 14},
        {"name": "Privilegio dello Specialista", "level": 15},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 16},
        {"name": "Esperto degli Oggetti Magici", "level": 18},
        {"name": "Aumento dei Punteggi di Caratteristica", "level": 19},
        {"name": "Anima dell'Artefice", "level": 20},
    ],
}

# Subclass features (more limited, best-effort)
SUBCLASS_FEATURES = {
    # ─── BARBARO ───────────────────────────────────────────────────────────────
    "Cammino del Berserker": [
        {"name": "Frenesia", "level": 3},
        {"name": "Ira Frenetica", "level": 6},
        {"name": "Presenza Intimidatoria", "level": 10},
        {"name": "Ritorsione", "level": 14},
    ],
    "Cammino del Combattente Totemico": [
        {"name": "Spirito del Totem", "level": 3},
        {"name": "Aspetto della Bestia", "level": 6},
        {"name": "Deambulatore dello Spirito", "level": 10},
        {"name": "Dono del Totem", "level": 14},
    ],
    "Cammino del Combattente": [
        {"name": "Armatura Chiodata", "level": 3},
        {"name": "Sfogo Blindato", "level": 6},
        {"name": "Istinto Difensivo", "level": 10},
        {"name": "Carica Corazzata", "level": 14},
    ],
    "Cammino del Kensei": [
        {"name": "Armi del Kensei", "level": 3},
        {"name": "Tiro del Kensei", "level": 6},
        {"name": "Uno con la Lama", "level": 11},
        {"name": "Mano Micidiale", "level": 17},
    ],
    "Cammino della Bestia": [
        {"name": "Forma della Bestia", "level": 3},
        {"name": "Aura Bestiale", "level": 6},
        {"name": "Spirito della Bestia Potenziato", "level": 10},
        {"name": "Chiama la Bestia", "level": 14},
    ],
    "Cammino della Furia Combattente": [
        {"name": "Armatura da Furia", "level": 3},
        {"name": "Sfogo della Furia", "level": 6},
        {"name": "Carica della Furia", "level": 10},
        {"name": "Frenesia Corazzata", "level": 14},
    ],
    "Cammino della Magia Selvaggia": [
        {"name": "Impulso Magico", "level": 3},
        {"name": "Anima della Magia Selvaggia", "level": 6},
        {"name": "Magia dell'Ira", "level": 10},
        {"name": "Deflagrazione Soprannaturale", "level": 14},
    ],
    "Cammino dello Zelota": [
        {"name": "Guerriero degli Dei", "level": 3},
        {"name": "Ira della Giustizia", "level": 3},
        {"name": "Fanatico Benedetto", "level": 6},
        {"name": "Presenza dello Zelota", "level": 10},
        {"name": "Spirito Indistruttibile", "level": 14},
    ],
    # ─── BARDO ─────────────────────────────────────────────────────────────────
    "Collegio della Sapienza": [
        {"name": "Competenze Bonus", "level": 3},
        {"name": "Critica Tagliente", "level": 3},
        {"name": "Parole di Terrore", "level": 6},
        {"name": "Segreti Magici Aggiuntivi", "level": 6},
        {"name": "Perfezione Insuperabile", "level": 14},
    ],
    "Collegio del Valore": [
        {"name": "Competenze Bonus", "level": 3},
        {"name": "Ispirazione Bellicosa", "level": 3},
        {"name": "Attacco Extra", "level": 6},
        {"name": "Magia da Battaglia", "level": 14},
    ],
    "Collegio dei Sussurri": [
        {"name": "Parole di Terrore", "level": 3},
        {"name": "Memorie Psichiche", "level": 3},
        {"name": "Mantello dei Bisbigliatori", "level": 6},
        {"name": "Ombra nella Mente", "level": 14},
    ],
    "Collegio dell Eloquenza": [
        {"name": "Argomento Infallibile", "level": 3},
        {"name": "Parola Rassicurante", "level": 3},
        {"name": "Lingua Universale", "level": 6},
        {"name": "Parola Virulenta", "level": 6},
        {"name": "Perorazione Magistrale", "level": 14},
    ],
    "Collegio dell'Incanto": [
        {"name": "Ammaliamento Fascinante", "level": 3},
        {"name": "Mantello delle Fate", "level": 3},
        {"name": "Magia Incantata", "level": 6},
        {"name": "Paradiso Incantevole", "level": 14},
    ],
    "Collegio della Creazione": [
        {"name": "Note di Potenziale", "level": 3},
        {"name": "Animare Performance", "level": 6},
        {"name": "Creazione Ispirata", "level": 14},
    ],
    "Collegio delle Spade": [
        {"name": "Competenze Bonus", "level": 3},
        {"name": "Lama Ispiratrice", "level": 3},
        {"name": "Attacco Extra", "level": 6},
        {"name": "Fiorita Devastante", "level": 14},
    ],
    "Collegio di Fochlucan": [
        {"name": "Canzone dei Boschi", "level": 3},
        {"name": "Canto Guaritore", "level": 6},
        {"name": "Parola del Fochlucan", "level": 14},
    ],
    "Collegio di Nuovo Olamn": [
        {"name": "Stile del Maestro", "level": 3},
        {"name": "Insegnamento Superiore", "level": 6},
        {"name": "Voce della Tradizione", "level": 14},
    ],
    # ─── CHIERICO ──────────────────────────────────────────────────────────────
    "Dominio della Vita": [
        {"name": "Guaritore Potenziato", "level": 1},
        {"name": "Incanalare Divinità: Conservare la Vita", "level": 2},
        {"name": "Cura dalla Vita", "level": 6},
        {"name": "Colpo Divino", "level": 8},
        {"name": "Guarigione Suprema", "level": 17},
    ],
    "Dominio della Luce": [
        {"name": "Trucchetto Bonus", "level": 1},
        {"name": "Scintilla Warding", "level": 1},
        {"name": "Incanalare Divinità: Raggi Radiosi", "level": 2},
        {"name": "Sole Migliorato", "level": 6},
        {"name": "Colpo Divino", "level": 8},
        {"name": "Corona della Luce", "level": 17},
    ],
    "Dominio della Guerra": [
        {"name": "Guerriero di Dio", "level": 1},
        {"name": "Incanalare Divinità: Guida Divina", "level": 2},
        {"name": "Sacerdote di Marte", "level": 6},
        {"name": "Colpo Divino", "level": 8},
        {"name": "Avatar della Battaglia", "level": 17},
    ],
    "Dominio della Conoscenza": [
        {"name": "Benedizione della Sete di Sapere", "level": 1},
        {"name": "Incanalare Divinità: Conoscenza degli Antichi", "level": 2},
        {"name": "Lettore dei Pensieri", "level": 6},
        {"name": "Colpo Potenziato", "level": 8},
        {"name": "Visioni del Passato", "level": 17},
    ],
    "Dominio della Natura": [
        {"name": "Servitore della Natura", "level": 1},
        {"name": "Incanalare Divinità: Charme Animali e Piante", "level": 2},
        {"name": "Resistenza Elementale", "level": 6},
        {"name": "Colpo Divino", "level": 8},
        {"name": "Signore della Natura", "level": 17},
    ],
    "Dominio della Tempesta": [
        {"name": "Ira della Tempesta", "level": 1},
        {"name": "Incanalare Divinità: Furia della Tempesta", "level": 2},
        {"name": "Striscia di Fulmine", "level": 6},
        {"name": "Colpo Divino", "level": 8},
        {"name": "Occhio della Tempesta", "level": 17},
    ],
    "Dominio dell'Inganno": [
        {"name": "Benedizione della Menzogna", "level": 1},
        {"name": "Incanalare Divinità: Invocare il Duplicato", "level": 2},
        {"name": "Benedizione dell'Impostora", "level": 6},
        {"name": "Colpo Ombra", "level": 8},
        {"name": "Icona dell'Inganno", "level": 17},
    ],
    "Dominio dell'Arcano": [
        {"name": "Studioso della Magia Arcana", "level": 1},
        {"name": "Incanalare Divinità: Dispersione Arcana", "level": 2},
        {"name": "Magia del Custode Arcano", "level": 6},
        {"name": "Colpo Potenziato", "level": 8},
        {"name": "Incantesimi Arcani Potenziati", "level": 17},
    ],
    "Dominio della Forgia": [
        {"name": "Benedizioni della Forgia", "level": 1},
        {"name": "Incanalare Divinità: Benedire il Forgiato", "level": 2},
        {"name": "Anima di Metallo", "level": 6},
        {"name": "Colpo Divino", "level": 8},
        {"name": "Santo Artefatto", "level": 17},
    ],
    # ─── DRUIDO ────────────────────────────────────────────────────────────────
    "Circolo della Terra": [
        {"name": "Incantesimi Naturali", "level": 2},
        {"name": "Passo Tellurgico", "level": 6},
        {"name": "Mente della Natura", "level": 10},
        {"name": "Santuario della Natura", "level": 14},
    ],
    "Circolo della Luna": [
        {"name": "Forma di Combattimento", "level": 2},
        {"name": "Luna Grigia", "level": 6},
        {"name": "Forma Elementale", "level": 10},
        {"name": "Mille Forme", "level": 14},
    ],
    "Circolo dei Sogni": [
        {"name": "Balsamo della Corte Estiva", "level": 2},
        {"name": "Passo nel Sogno", "level": 6},
        {"name": "Viaggio nei Sogni", "level": 10},
        {"name": "Presenza dei Sogni", "level": 14},
    ],
    "Circolo del Pastore": [
        {"name": "Parlare con gli Spiriti", "level": 2},
        {"name": "Segnale degli Spiriti", "level": 2},
        {"name": "Protezione Mistica", "level": 6},
        {"name": "Incantesimo Fedele", "level": 10},
        {"name": "Signore del Gregge", "level": 14},
    ],
    "Circolo della Fiamma": [
        {"name": "Fiamma dello Spirito", "level": 2},
        {"name": "Abbraccio della Fiamma", "level": 6},
        {"name": "Ardore della Fiamma", "level": 10},
        {"name": "Rinnovamento della Fiamma", "level": 14},
    ],
    "Circolo delle Spore": [
        {"name": "Lingua dei Funghi", "level": 2},
        {"name": "Alone di Spore", "level": 2},
        {"name": "Simbiosi", "level": 6},
        {"name": "Scudo Fungino", "level": 10},
        {"name": "Entità Simbiotica", "level": 14},
    ],
    "Circolo delle Stelle": [
        {"name": "Mappa Stellare", "level": 2},
        {"name": "Forma Stellare", "level": 2},
        {"name": "Cosmo Guaritore", "level": 6},
        {"name": "Stardust", "level": 10},
        {"name": "Frequenza Stellare", "level": 14},
    ],
    # ─── GUERRIERO ─────────────────────────────────────────────────────────────
    "Campione": [
        {"name": "Critico Superiore", "level": 3},
        {"name": "Studioso dell'Atletica", "level": 7},
        {"name": "Stile di Combattimento Aggiuntivo", "level": 10},
        {"name": "Critico Superiore (19-20)", "level": 15},
        {"name": "Sopravvissuto", "level": 18},
    ],
    "Maestro di Battaglia": [
        {"name": "Manovre di Combattimento", "level": 3},
        {"name": "Dadi Superiorità", "level": 3},
        {"name": "Studioso della Guerra", "level": 3},
        {"name": "Conoscere il Nemico", "level": 7},
        {"name": "Dadi Superiorità Migliorati", "level": 10},
        {"name": "Implacabile", "level": 15},
        {"name": "Padronanza delle Manovre", "level": 18},
    ],
    "Cavaliere Mistico": [
        {"name": "Incantesimi", "level": 3},
        {"name": "Legame d'Arma", "level": 3},
        {"name": "Guerra Magica", "level": 7},
        {"name": "Incantesimo del Cavaliere Mistico", "level": 10},
        {"name": "Carica Arcana", "level": 15},
        {"name": "Colpo Mistico Migliorato", "level": 18},
    ],
    "Arciere Arcano": [
        {"name": "Freccia Arcana", "level": 3},
        {"name": "Magie delle Frecce Arcane", "level": 3},
        {"name": "Passo Furtivo Magico", "level": 7},
        {"name": "Magia della Guida", "level": 10},
        {"name": "Frecce Arcane Sempre Pronte", "level": 15},
        {"name": "Arciere Arcano Maestro", "level": 18},
    ],
    "Cavaliere Errante": [
        {"name": "Disciplina del Combattente Errante", "level": 3},
        {"name": "Combattente Indomito", "level": 7},
        {"name": "Carica del Cavaliere", "level": 10},
        {"name": "Lancia del Cavaliere", "level": 15},
        {"name": "Cavaliere Supremo", "level": 18},
    ],
    "Samurai": [
        {"name": "Fortuna del Coraggioso", "level": 3},
        {"name": "Grazia Elegante", "level": 7},
        {"name": "Resistenza dei Guerrieri", "level": 10},
        {"name": "Rapido Guadagno", "level": 15},
        {"name": "Forza dell'Onore", "level": 18},
    ],
    "Cavaliere Runico": [
        {"name": "Incisione Runica", "level": 3},
        {"name": "Maestro delle Rune", "level": 3},
        {"name": "Carica Runica", "level": 7},
        {"name": "Aura del Guardiano", "level": 10},
        {"name": "Comando delle Rune", "level": 15},
        {"name": "Signore delle Rune", "level": 18},
    ],
    "Guerriero Psionico": [
        {"name": "Mente Potenziata", "level": 3},
        {"name": "Aura Psichica", "level": 3},
        {"name": "Guardia Psichica", "level": 7},
        {"name": "Corpo Psionico", "level": 10},
        {"name": "Telecinesi Psionicissima", "level": 15},
        {"name": "Colosso Psionico", "level": 18},
    ],
    # ─── LADRO ─────────────────────────────────────────────────────────────────
    "Ladro": [
        {"name": "Competenza Esperta Aggiuntiva", "level": 3},
        {"name": "Sensi Supremi", "level": 9},
        {"name": "Applicazione Magica", "level": 13},
        {"name": "Colpo Infallibile", "level": 17},
    ],
    "Assassino": [
        {"name": "Competenze Bonus", "level": 3},
        {"name": "Assassinare", "level": 3},
        {"name": "Infiltrazione", "level": 9},
        {"name": "Impostora", "level": 13},
        {"name": "Colpo Mortale", "level": 17},
    ],
    "Mistificatore Arcano": [
        {"name": "Incantesimi", "level": 3},
        {"name": "Trucchetti Magici", "level": 3},
        {"name": "Invocazione Magica", "level": 9},
        {"name": "Magia Ladra", "level": 13},
        {"name": "Ladro Magico", "level": 17},
    ],
    "Esploratore": [
        {"name": "Occhio dell'Esploratore", "level": 3},
        {"name": "Conoscenza della Zona Naturale", "level": 3},
        {"name": "Sensi Superiori", "level": 9},
        {"name": "Vista dell'Esploratore", "level": 13},
        {"name": "Mente Elusiva", "level": 17},
    ],
    "Indagatore": [
        {"name": "Scena del Crimine", "level": 3},
        {"name": "Orecchio del Detective", "level": 9},
        {"name": "Vista Acuta", "level": 13},
        {"name": "Mente del Detective", "level": 17},
    ],
    "Pianificatore": [
        {"name": "Ricognizione Suprema", "level": 3},
        {"name": "Piano di Fuga", "level": 9},
        {"name": "Azione Preparata", "level": 13},
        {"name": "Piano di Riserva", "level": 17},
    ],
    "Spadaccino": [
        {"name": "Passi Eleganti", "level": 3},
        {"name": "Insulto Abile", "level": 3},
        {"name": "Posizione Bravata", "level": 9},
        {"name": "Destino del Duellante", "level": 13},
        {"name": "Maestro del Duello", "level": 17},
    ],
    "Fantasma": [
        {"name": "Passi Spettrali", "level": 3},
        {"name": "Spogliare la Psiche", "level": 3},
        {"name": "Passo Spettrale", "level": 9},
        {"name": "Fantasma Incarnato", "level": 13},
        {"name": "Sguardo della Morte", "level": 17},
    ],
    "Lama Spirituale": [
        {"name": "Evocazione della Lama Spirituale", "level": 3},
        {"name": "Soffio Spiritoso", "level": 3},
        {"name": "Piegatura dell'Anima", "level": 9},
        {"name": "Difesa Spettrale", "level": 13},
        {"name": "Legame dell'Anima", "level": 17},
    ],
    # ─── MAGO ──────────────────────────────────────────────────────────────────
    "Scuola di Abiurazione": [
        {"name": "Apprendimento dell'Abiurazione", "level": 2},
        {"name": "Protezione Arcana", "level": 2},
        {"name": "Abiurazione Proiettata", "level": 6},
        {"name": "Resistenza Migliorata", "level": 10},
        {"name": "Protezione Arcana Suprema", "level": 14},
    ],
    "Scuola di Ammaliamento": [
        {"name": "Incantatore Dotato", "level": 2},
        {"name": "Incantesimo Ipnotico", "level": 2},
        {"name": "Forma la Mente", "level": 6},
        {"name": "Fascino Controllato", "level": 10},
        {"name": "Fascino Alterato", "level": 14},
    ],
    "Scuola di Divinazione": [
        {"name": "Portento", "level": 2},
        {"name": "Apprendimento della Divinazione", "level": 2},
        {"name": "Terzo Occhio", "level": 6},
        {"name": "Portento Migliorato", "level": 10},
        {"name": "Profezia Suprema", "level": 14},
    ],
    "Scuola di Evocazione": [
        {"name": "Scolpire Incantesimi", "level": 2},
        {"name": "Apprendimento dell'Evocazione", "level": 2},
        {"name": "Minimo Impatto", "level": 6},
        {"name": "Sovrappotere Incantesimi", "level": 10},
        {"name": "Distruzione Suprema", "level": 14},
    ],
    "Scuola di Illusione": [
        {"name": "Illusore Migliorato", "level": 2},
        {"name": "Apprendimento dell'Illusione", "level": 2},
        {"name": "Illusione Malleabile", "level": 6},
        {"name": "Doppio Illusorio", "level": 10},
        {"name": "Illusione della Realtà", "level": 14},
    ],
    "Scuola di Invocazione": [
        {"name": "Apprendimento dell'Invocazione", "level": 2},
        {"name": "Distorcere lo Spazio", "level": 2},
        {"name": "Passi del Vento", "level": 6},
        {"name": "Portale Spontaneo", "level": 10},
        {"name": "Distorsione Temporale", "level": 14},
    ],
    "Scuola di Necromanzia": [
        {"name": "Apprendimento della Necromanzia", "level": 2},
        {"name": "Studio dei Morti", "level": 2},
        {"name": "Esercito Morto-Vivente", "level": 6},
        {"name": "Tocco Letale", "level": 10},
        {"name": "Signore dei Non-Morti", "level": 14},
    ],
    "Scuola di Trasmutazione": [
        {"name": "Apprendimento della Trasmutazione", "level": 2},
        {"name": "Alchimia Minore", "level": 2},
        {"name": "Pietra del Trasmutatore", "level": 6},
        {"name": "Morfo", "level": 10},
        {"name": "Padrone della Trasmutazione", "level": 14},
    ],
    "Magia della Guerra": [
        {"name": "Studio Arcano", "level": 2},
        {"name": "Deviazione Arcana", "level": 2},
        {"name": "Tattiche di Guerra", "level": 6},
        {"name": "Potere delle Rune", "level": 10},
        {"name": "Difesa del Guerriero Arcano", "level": 14},
        {"name": "Supremazia di Guerra", "level": 18},
    ],
    "Canto della Lama": [
        {"name": "Addestramento con le Armi", "level": 2},
        {"name": "Canto della Lama", "level": 2},
        {"name": "Attacco Extra", "level": 6},
        {"name": "Canto della Furia", "level": 10},
        {"name": "Canto della Vittoria", "level": 14},
    ],
    "Ordine degli Scribi": [
        {"name": "Calamo Incantato", "level": 2},
        {"name": "Libro degli Incantesimi Risvegliato", "level": 2},
        {"name": "Mente Manifesta", "level": 6},
        {"name": "Una con la Parola", "level": 10},
        {"name": "Archivio Inesauribile", "level": 14},
    ],
    # ─── MONACO ────────────────────────────────────────────────────────────────
    "Via della Mano Aperta": [
        {"name": "Tecnica della Mano Aperta", "level": 3},
        {"name": "Corpo Integro", "level": 6},
        {"name": "Tranquillità", "level": 11},
        {"name": "Palmo di Vibrazione", "level": 17},
    ],
    "Via dell'Ombra": [
        {"name": "Arti dell'Ombra", "level": 3},
        {"name": "Passo nelle Ombre", "level": 6},
        {"name": "Mantello delle Notti", "level": 11},
        {"name": "Tessitore delle Ombre", "level": 17},
    ],
    "Via dei Quattro Elementi": [
        {"name": "Discepolo degli Elementi", "level": 3},
        {"name": "Disciplina degli Elementi Avanzata", "level": 6},
        {"name": "Passo del Vento", "level": 11},
        {"name": "Padrone degli Elementi", "level": 17},
    ],
    "Via del Kensei": [
        {"name": "Armi del Kensei", "level": 3},
        {"name": "Uno con il Filo della Lama", "level": 6},
        {"name": "Forma Aguzza della Lama", "level": 11},
        {"name": "Mano Micidiale", "level": 17},
    ],
    "Via del Maestro Ubriaco": [
        {"name": "Tecniche Ubriache", "level": 3},
        {"name": "Riequilibrio Ubriaco", "level": 6},
        {"name": "Ubriachezza Profonda", "level": 11},
        {"name": "Maestro dell'Ubriacone", "level": 17},
    ],
    "Via del Male": [
        {"name": "Coltivare il Buio", "level": 3},
        {"name": "Mano del Male", "level": 6},
        {"name": "Anima del Male", "level": 11},
        {"name": "Padrone dell'Oscurità", "level": 17},
    ],
    "Via del Se Astrale": [
        {"name": "Evocazione del Sé Astrale", "level": 3},
        {"name": "Braccio del Sé Astrale", "level": 6},
        {"name": "Corpo del Sé Astrale", "level": 11},
        {"name": "Essere Risvegliato", "level": 17},
    ],
    "Via dell'Anima Solare": [
        {"name": "Colpo Radiante", "level": 3},
        {"name": "Raggi Solari", "level": 3},
        {"name": "Riflesso Solare", "level": 6},
        {"name": "Forma Solare", "level": 11},
        {"name": "Esplosione Solare", "level": 17},
    ],
    "Via della Lunga Morte": [
        {"name": "Tocco della Morte", "level": 3},
        {"name": "Ora della Mietitura", "level": 6},
        {"name": "Mascherare la Morte", "level": 11},
        {"name": "Tocco dell'Agonia", "level": 17},
    ],
    "Via della Misericordia Do": [
        {"name": "Mani di Guarigione", "level": 3},
        {"name": "Mani di Danno", "level": 3},
        {"name": "Medicante delle Anime", "level": 6},
        {"name": "Pietà", "level": 11},
        {"name": "Tocco della Morte Misericordioso", "level": 17},
    ],
    # ─── PALADINO ──────────────────────────────────────────────────────────────
    "Giuramento di Devozione": [
        {"name": "Incantesimi del Giuramento", "level": 3},
        {"name": "Incanalare Divinità: Armamento Sacro", "level": 3},
        {"name": "Incanalare Divinità: Luce Sacra", "level": 3},
        {"name": "Aura della Devozione", "level": 7},
        {"name": "Purezza dello Spirito", "level": 15},
        {"name": "Nimbo Santo", "level": 20},
    ],
    "Giuramento degli Antichi": [
        {"name": "Incantesimi del Giuramento", "level": 3},
        {"name": "Incanalare Divinità: Cuore della Natura", "level": 3},
        {"name": "Incanalare Divinità: Compagno della Foresta", "level": 3},
        {"name": "Resistenza dell'Aura", "level": 7},
        {"name": "Protezione Sempreverde", "level": 15},
        {"name": "Campione degli Antichi Dei", "level": 20},
    ],
    "Giuramento di Vendetta": [
        {"name": "Incantesimi del Giuramento", "level": 3},
        {"name": "Incanalare Divinità: Maledizione dell'Empio", "level": 3},
        {"name": "Incanalare Divinità: Voto dell'Inimicizia", "level": 3},
        {"name": "Impietosa", "level": 7},
        {"name": "Spirito Vendicativo", "level": 15},
        {"name": "Angelo della Vendetta", "level": 20},
    ],
    "Giuramento della Corona": [
        {"name": "Incantesimi del Giuramento", "level": 3},
        {"name": "Incanalare Divinità: Assalto della Corona", "level": 3},
        {"name": "Incanalare Divinità: Turno dei Non-Morti", "level": 3},
        {"name": "Aura della Legge", "level": 7},
        {"name": "Bastion of Law", "level": 15},
        {"name": "Paladino Eterno", "level": 20},
    ],
    "Giuramento delle Sentinelle": [
        {"name": "Incantesimi del Giuramento", "level": 3},
        {"name": "Incanalare Divinità: Recupero del Malfattore", "level": 3},
        {"name": "Incanalare Divinità: Oblio Benedetto", "level": 3},
        {"name": "Aura della Sentinella", "level": 7},
        {"name": "Protezione delle Sentinelle", "level": 15},
        {"name": "Forma delle Sentinelle", "level": 20},
    ],
    "Giuramento di Conquista": [
        {"name": "Incantesimi del Giuramento", "level": 3},
        {"name": "Incanalare Divinità: Conquista Schiacciante", "level": 3},
        {"name": "Incanalare Divinità: Smaltimento della Paura", "level": 3},
        {"name": "Aura di Conquista", "level": 7},
        {"name": "Scudo Agghiacciante", "level": 15},
        {"name": "Forma Invincibile", "level": 20},
    ],
    "Giuramento di Gloria": [
        {"name": "Incantesimi del Giuramento", "level": 3},
        {"name": "Incanalare Divinità: Ispirare Campioni", "level": 3},
        {"name": "Incanalare Divinità: Petto del Glorioso", "level": 3},
        {"name": "Aura della Gloria", "level": 7},
        {"name": "Eroismo Glorioso", "level": 15},
        {"name": "Avatar della Gloria", "level": 20},
    ],
    "Giuramento di Inimicizia": [
        {"name": "Incantesimi del Giuramento", "level": 3},
        {"name": "Incanalare Divinità: Controllo dei Non-Morti", "level": 3},
        {"name": "Incanalare Divinità: Maledizione del Rinnegato", "level": 3},
        {"name": "Aura dell'Odio", "level": 7},
        {"name": "Non-Morto Benedetto", "level": 15},
        {"name": "Signore dei Non-Morti", "level": 20},
    ],
    # ─── RANGER ────────────────────────────────────────────────────────────────
    "Cacciatore": [
        {"name": "Preda del Cacciatore", "level": 3},
        {"name": "Tattiche Difensive", "level": 7},
        {"name": "Attacchi Multipli", "level": 11},
        {"name": "Difesa del Cacciatore Superiore", "level": 15},
    ],
    "Signore delle Bestie": [
        {"name": "Compagno Animale", "level": 3},
        {"name": "Addestramento Eccezionale", "level": 7},
        {"name": "Furia Bestiale", "level": 11},
        {"name": "Condivisione degli Incantesimi", "level": 15},
    ],
    "Cacciatore delle Tenebre": [
        {"name": "Punta Feroce", "level": 3},
        {"name": "Resistenza alla Magia", "level": 7},
        {"name": "Consumare le Tenebre", "level": 11},
        {"name": "Sensi Spettrali", "level": 15},
    ],
    "Uccisore di Mostri": [
        {"name": "Cacciatore Difensivo", "level": 3},
        {"name": "Sensi del Mostro", "level": 3},
        {"name": "Cacciatore Letale", "level": 7},
        {"name": "Resistenza Suprema", "level": 11},
        {"name": "Uccisore Supremo", "level": 15},
    ],
    "Custode degli Sciami": [
        {"name": "Compagno dello Sciame", "level": 3},
        {"name": "Sciame Minaccioso", "level": 7},
        {"name": "Sciame Protettivo", "level": 11},
        {"name": "Sciame Supremo", "level": 15},
    ],
    "Viandante Fatato": [
        {"name": "Portale Fatato", "level": 3},
        {"name": "Bendaggio della Fata", "level": 7},
        {"name": "Perdita nella Nebbia", "level": 11},
        {"name": "Scudo del Fatato", "level": 15},
    ],
    # ─── STREGONE ──────────────────────────────────────────────────────────────
    "Discendenza Draconica": [
        {"name": "Antenato Draconico", "level": 1},
        {"name": "Resilienza Draconica", "level": 1},
        {"name": "Affinità Elementale", "level": 6},
        {"name": "Ali del Drago", "level": 14},
        {"name": "Presenza Draconica", "level": 18},
    ],
    "Magia Selvaggia": [
        {"name": "Scossa di Magia Selvaggia", "level": 1},
        {"name": "Onda Fortuita", "level": 1},
        {"name": "Magia Controllata", "level": 6},
        {"name": "Piegatura della Sorte", "level": 14},
        {"name": "Scarica Controllata", "level": 18},
    ],
    "Anima Divina": [
        {"name": "Magia Divina", "level": 1},
        {"name": "Ala Angelica", "level": 6},
        {"name": "Forma Eterea", "level": 14},
        {"name": "Trascendenza dell'Anima", "level": 18},
    ],
    "Magia delle Ombre": [
        {"name": "Occhi delle Tenebre", "level": 1},
        {"name": "Forza dell'Ade", "level": 1},
        {"name": "Imboscata delle Ombre", "level": 6},
        {"name": "Passeggiata delle Ombre", "level": 14},
        {"name": "Forma delle Ombre", "level": 18},
    ],
    "Stregoneria della Tempesta": [
        {"name": "Vento delle Tempeste", "level": 1},
        {"name": "Cuore della Tempesta", "level": 1},
        {"name": "Tempesta in Movimento", "level": 6},
        {"name": "Furia della Tempesta", "level": 14},
        {"name": "Anima della Tempesta", "level": 18},
    ],
    "Anima Meccanica": [
        {"name": "Guardia di Ferro", "level": 1},
        {"name": "Magia del Costrutto", "level": 6},
        {"name": "Forma Automata", "level": 14},
        {"name": "Incorporazione Meccanica", "level": 18},
    ],
    "Mente Aberrante": [
        {"name": "Tentacoli Telepatici", "level": 1},
        {"name": "Corpo Aberrante", "level": 6},
        {"name": "Occhio Alieno", "level": 14},
        {"name": "Forma Aberrante", "level": 18},
    ],
    # ─── WARLOCK ───────────────────────────────────────────────────────────────
    "L'Immondo": [
        {"name": "Incantesimi Espansi", "level": 1},
        {"name": "Benedizione dell'Oscuro", "level": 1},
        {"name": "Propria Fortuna", "level": 6},
        {"name": "Parole dell'Oscuro Sovrano", "level": 10},
        {"name": "Forma dell'Oscuro Signore", "level": 14},
    ],
    "Il Grande Antico": [
        {"name": "Incantesimi Espansi", "level": 1},
        {"name": "Mente Risvegliata", "level": 1},
        {"name": "Difesa Entropica", "level": 6},
        {"name": "Comunione del Pensiero", "level": 10},
        {"name": "Creare Aberrazione", "level": 14},
    ],
    "Il Signore Fatato": [
        {"name": "Incantesimi Espansi", "level": 1},
        {"name": "Presenza Fatata", "level": 1},
        {"name": "Passo Fatato", "level": 6},
        {"name": "Bacio Oscuro", "level": 10},
        {"name": "Fantasia Oscura", "level": 14},
    ],
    "Il Celestiale": [
        {"name": "Trucchetti Bonus", "level": 1},
        {"name": "Incantesimi Espansi", "level": 1},
        {"name": "Saggezza Guaritrice", "level": 6},
        {"name": "Benedizione del Celeste", "level": 10},
        {"name": "Ala di Serafino", "level": 14},
    ],
    "La Lama del Sortilegio": [
        {"name": "Maledizione della Lama del Sortilegio", "level": 1},
        {"name": "Patto della Lama Potenziato", "level": 1},
        {"name": "Lama Esacerbata", "level": 6},
        {"name": "Anima della Lama", "level": 10},
        {"name": "Collisione dei Destini", "level": 14},
    ],
    "Il Genio": [
        {"name": "Vaso del Genio", "level": 1},
        {"name": "Incantesimi Espansi", "level": 1},
        {"name": "Ingresso nel Vaso", "level": 6},
        {"name": "Doni del Genio", "level": 10},
        {"name": "Forma della Lampada", "level": 14},
    ],
    "L'Insondabile": [
        {"name": "Tentacolo del Leviatano", "level": 1},
        {"name": "Voce dei Fondali", "level": 1},
        {"name": "Protezione del Profondo", "level": 6},
        {"name": "Trasformazione del Profondo", "level": 10},
        {"name": "Forma dell'Insondabile", "level": 14},
    ],
    # ─── ARTEFICE — Specialisti (Tasha) ───────────────────────────────────────
    "Alchimista": [
        {"name": "Competenza con Strumenti", "level": 3},
        {"name": "Incantesimi dello Specialista", "level": 3},
        {"name": "Pozioni dell'Alchimista", "level": 3},
        {"name": "Savant Alchemico", "level": 5},
        {"name": "Riassetto Restaurativo", "level": 9},
        {"name": "Salvatore Chimico", "level": 15},
    ],
    "Artigliere": [
        {"name": "Competenza con Strumenti", "level": 3},
        {"name": "Incantesimi dello Specialista", "level": 3},
        {"name": "Cannone Eldritch", "level": 3},
        {"name": "Forza Arcana", "level": 5},
        {"name": "Devastatore Esplosivo", "level": 9},
        {"name": "Distruzione Fulminea", "level": 15},
    ],
    "Forgia di Battaglia": [
        {"name": "Competenza con Strumenti", "level": 3},
        {"name": "Incantesimi dello Specialista", "level": 3},
        {"name": "Combattimento dell'Artefice", "level": 3},
        {"name": "Compagno d'Acciaio", "level": 3},
        {"name": "Estratto Curativo", "level": 5},
        {"name": "Riparazione Arcana", "level": 9},
        {"name": "Jolt di Memoria Improvviso", "level": 15},
    ],
    "Armaiolo": [
        {"name": "Competenza con Strumenti", "level": 3},
        {"name": "Incantesimi dello Specialista", "level": 3},
        {"name": "Armatura dell'Artefice", "level": 3},
        {"name": "Modello Arma", "level": 3},
        {"name": "Modifiche all'Armatura Estese", "level": 5},
        {"name": "Soppressore Arcano", "level": 9},
        {"name": "Padronanza dell'Armatura", "level": 15},
    ],
}

# Race features
RACE_FEATURES = {
    "Alto Elfo": [
        {"name": "Sensi Acuti", "desc": "Competenza nell'abilità Percezione."},
        {"name": "Ascendenza Fatata", "desc": "Vantaggio ai tiri salvezza contro l'essere incantato e la magia non può farti addormentare."},
        {"name": "Trance", "desc": "Gli elfi non dormono. Invece meditano in trance per 4 ore al giorno."},
        {"name": "Maestria delle Armi Elfiche", "desc": "Competenza con spada lunga, spada corta, arco corto e arco lungo."},
        {"name": "Trucchetto Bonus", "desc": "Conosci un trucchetto a tua scelta dalla lista degli incantesimi del mago."},
        {"name": "Lingua Aggiuntiva", "desc": "Parli, leggi e scrivi una lingua aggiuntiva a tua scelta."},
    ],
    "Elfo del Bosco": [
        {"name": "Sensi Acuti", "desc": "Competenza nell'abilità Percezione."},
        {"name": "Ascendenza Fatata", "desc": "Vantaggio ai tiri salvezza contro l'essere incantato e la magia non può farti addormentare."},
        {"name": "Trance", "desc": "Gli elfi non dormono. Invece meditano in trance per 4 ore al giorno."},
        {"name": "Maestria delle Armi Elfiche", "desc": "Competenza con spada lunga, spada corta, arco corto e arco lungo."},
        {"name": "Passo Veloce", "desc": "La tua velocità base di camminata è 10,5 m (35 piedi)."},
        {"name": "Mascherare i Passi", "desc": "Puoi tentare di nasconderti anche quando sei solo leggermente oscurato da fogliame, pioggia forte, neve che cade, nebbia e altri fenomeni naturali."},
    ],
    "Drow": [
        {"name": "Superiorità della Vista nell'Oscurità", "desc": "La tua visione nella oscurità è superiore a quella dei normali elfi: vedi in condizioni di oscurità entro 36 m come se fosse tenue luminosità."},
        {"name": "Sensibilità alla Luce Solare", "desc": "Svantaggio ai tiri per colpire e alle prove di Percezione basate sulla vista quando tu o il tuo bersaglio siete esposti alla luce solare diretta."},
        {"name": "Magia del Drow", "desc": "Conosci il trucchetto luci danzanti. Al 3° livello puoi lanciare fata fuoco una volta al giorno. Al 5° livello puoi lanciare oscurità una volta al giorno."},
        {"name": "Competenza in Armi del Drow", "desc": "Competenza con rapiera, spada corta e balestra a mano."},
    ],
    "Nano delle Colline": [
        {"name": "Visione nella Oscurità", "desc": "Puoi vedere in condizioni di oscurità entro 18 m come se fosse tenue luminosità."},
        {"name": "Resistenza dei Nani", "desc": "Vantaggio ai tiri salvezza contro il veleno e resistenza ai danni da veleno."},
        {"name": "Addestramento al Combattimento dei Nani", "desc": "Competenza con ascia, ascia bipenne, martello da guerra e martello."},
        {"name": "Competenza negli Strumenti", "desc": "Competenza con gli strumenti artigianali di tua scelta."},
        {"name": "Stabilità dei Nani", "desc": "Vantaggio ai tiri salvezza per non essere atterrato quando viene tentata una spinta, e vantaggio nelle prove di resistenza allo spostamento."},
        {"name": "Tenacia dei Nani delle Colline", "desc": "Il tuo massimo di punti ferita aumenta di 1 e aumenta di 1 ogni volta che sali di livello."},
    ],
    "Nano delle Montagne": [
        {"name": "Visione nella Oscurità", "desc": "Puoi vedere in condizioni di oscurità entro 18 m come se fosse tenue luminosità."},
        {"name": "Resistenza dei Nani", "desc": "Vantaggio ai tiri salvezza contro il veleno e resistenza ai danni da veleno."},
        {"name": "Addestramento al Combattimento dei Nani", "desc": "Competenza con ascia, ascia bipenne, martello da guerra e martello."},
        {"name": "Competenza con l'Armatura dei Nani delle Montagne", "desc": "Hai competenza con l'armatura leggera e media."},
    ],
    "Umano": [
        {"name": "Bonus alle Caratteristiche", "desc": "Punteggi di caratteristica aumentati di 1 ciascuno."},
        {"name": "Lingue", "desc": "Parli, leggi e scrivi il Comune e una lingua aggiuntiva a tua scelta."},
    ],
    "Umano Variante": [
        {"name": "Bonus alle Caratteristiche", "desc": "Due punteggi di caratteristica a tua scelta aumentano di 1."},
        {"name": "Competenza Bonus", "desc": "Acquisisci competenza in una abilità a tua scelta."},
        {"name": "Talento", "desc": "Guadagni un talento a tua scelta."},
    ],
    "Halfling Piedelesto": [
        {"name": "Fortuna", "desc": "Quando ottieni un 1 in un tiro per colpire, tiro su tabella degli effetti o tiro salvezza, puoi ritirare il dado e devi usare il nuovo risultato."},
        {"name": "Coraggio", "desc": "Vantaggio ai tiri salvezza contro la paura."},
        {"name": "Agilità degli Halfling", "desc": "Puoi muoverti attraverso lo spazio di qualsiasi creatura di taglia più grande della tua."},
        {"name": "Piede Silenzioso", "desc": "Puoi tentare di nasconderti anche quando sei oscurato solo da una creatura di taglia Medio o più grande."},
    ],
    "Halfling Robusto": [
        {"name": "Fortuna", "desc": "Quando ottieni un 1 in un tiro per colpire, tiro su tabella degli effetti o tiro salvezza, puoi ritirare il dado e devi usare il nuovo risultato."},
        {"name": "Coraggio", "desc": "Vantaggio ai tiri salvezza contro la paura."},
        {"name": "Agilità degli Halfling", "desc": "Puoi muoverti attraverso lo spazio di qualsiasi creatura di taglia più grande della tua."},
        {"name": "Resistenza dei Robusti", "desc": "Vantaggio ai tiri salvezza contro il veleno e resistenza ai danni da veleno."},
    ],
    "Tiefling": [
        {"name": "Visione nella Oscurità", "desc": "Puoi vedere in condizioni di oscurità entro 18 m come se fosse tenue luminosità."},
        {"name": "Resistenza Infernale", "desc": "Resistenza ai danni da fuoco."},
        {"name": "Retaggio Infernale", "desc": "Conosci il trucchetto prestidigitazione. Al 3° livello puoi lanciare bruciatura infernale una volta al giorno. Al 5° livello puoi lanciare oscurità una volta al giorno."},
    ],
    "Dragonide": [
        {"name": "Antenato Dracomorfico", "desc": "Hai un tipo di drago come antenato, che determina il tipo di danni e la forma del tuo soffio."},
        {"name": "Soffio", "desc": "Puoi usare la tua azione per esalare energia distruttiva."},
        {"name": "Resistenza ai Danni", "desc": "Resistenza al tipo di danno associato al tuo antenato dracomorfico."},
    ],
    "Gnomo delle Foreste": [
        {"name": "Visione nella Oscurità", "desc": "Puoi vedere in condizioni di oscurità entro 18 m come se fosse tenue luminosità."},
        {"name": "Astuzia degli Gnomi", "desc": "Vantaggio ai tiri salvezza su Intelligenza, Saggezza e Carisma contro la magia."},
        {"name": "Illusione Naturale", "desc": "Conosci il trucchetto illusione minore."},
        {"name": "Parlare con le Bestie", "desc": "Puoi comunicare concetti semplici con bestie di taglia Piccola o più piccola."},
    ],
    "Gnomo delle Rocce": [
        {"name": "Visione nella Oscurità", "desc": "Puoi vedere in condizioni di oscurità entro 18 m come se fosse tenue luminosità."},
        {"name": "Astuzia degli Gnomi", "desc": "Vantaggio ai tiri salvezza su Intelligenza, Saggezza e Carisma contro la magia."},
        {"name": "Conoscitore Artigianale", "desc": "Competenza con strumenti artigianali: puoi creare aggeggi meccanici."},
        {"name": "Storico", "desc": "Doppia competenza nelle prove di Storia relative a oggetti magici, manufatti alchemici o dispositivi tecnologici."},
    ],
    "Mezz'Elfo": [
        {"name": "Visione nella Oscurità", "desc": "Puoi vedere in condizioni di oscurità entro 18 m come se fosse tenue luminosità."},
        {"name": "Ascendenza Fatata", "desc": "Vantaggio ai tiri salvezza contro l'essere incantato e la magia non può farti addormentare."},
        {"name": "Carattere Versatile", "desc": "Acquisisci competenza in due abilità a tua scelta."},
    ],
    "Mezzorco": [
        {"name": "Visione nella Oscurità", "desc": "Puoi vedere in condizioni di oscurità entro 18 m come se fosse tenue luminosità."},
        {"name": "Resistenza Minacciosa", "desc": "Competenza nell'abilità Intimidire."},
        {"name": "Implacabile", "desc": "Quando vieni ridotto a 0 PF ma non sei ucciso immediatamente, puoi invece avere 1 PF. Non puoi usare questo privilegio di nuovo finché non completi un riposo lungo."},
        {"name": "Attacchi Selvaggi", "desc": "Quando ottieni un colpo critico con un'arma da mischia, puoi tirare uno dei dadi del danno dell'arma una volta in più e aggiungerlo al danno."},
    ],
}

# Background features (privilegio principale di ogni background)
BACKGROUND_FEATURES = {
    "Accademico": [
        {"name": "Ricercatore", "desc": "Quando tenti di imparare o ricordare un pezzo di sapere, se non conosci l'informazione, spesso sai dove e da chi puoi ottenerla."}
    ],
    "Acrobata": [
        {"name": "Nomade per Mestiere", "desc": "Puoi trovare sempre un posto dove dormire, mangiare e mettere al sicuro il tuo equipaggiamento nei pressi di un centro abitato, in cambio di un piccolo spettacolo."}
    ],
    "Artigiano di Gilda": [
        {"name": "Membro della Gilda", "desc": "Le gilde sono onnipresenti. Puoi contare sull'aiuto dei confratelli e trovare rifugio nelle case della gilda in ogni città."}
    ],
    "Cavaliere": [
        {"name": "Posizione di Privilegio", "desc": "Grazie alla tua nascita nobile, la gente assume che tu abbia il diritto di essere dove sei. I nobili ti trattano come un loro pari."}
    ],
    "Cercatore di Fortuna": [
        {"name": "Falsa Identità", "desc": "Hai creato una seconda identità che include documenti, contatti e travestimenti. Puoi anche contraffarre documenti."}
    ],
    "Criminale": [
        {"name": "Contatto Criminale", "desc": "Hai un contatto affidabile e di fiducia che funge da collegamento con una rete più ampia di criminali."}
    ],
    "Eremita": [
        {"name": "Scoperta", "desc": "Il tuo isolamento ti ha permesso di scoprire una grande verità o una potente rivelazione, che il DM stabilirà con te."}
    ],
    "Emarginato": [
        {"name": "Rifugio degli Emarginati", "desc": "Trovi rifugio tra gli altri emarginati. Possono aiutarti a nasconderti, recuperare informazioni o ottenere semplici favori."}
    ],
    "Eroe del Popolo": [
        {"name": "Ospitalità Rustica", "desc": "Poiché sei uno di loro, la gente comune ti supporterà nascondendoti, dandoti da mangiare e informandoti."}
    ],
    "Marinaio": [
        {"name": "Passo di Banchina", "desc": "Quando hai bisogno di un passaggio su una nave, puoi sempre trovare un imbarco gratuito o a basso costo."}
    ],
    "Nobile": [
        {"name": "Posizione di Privilegio", "desc": "Grazie alla tua nascita nobile, la gente assume che tu abbia il diritto di essere dove sei. I nobili ti trattano come un loro pari."}
    ],
    "Orfano di Strada": [
        {"name": "Rete Cittadina", "desc": "Conosci i segreti della città: dove nascondersi, dove trovare informazioni, e come muoversi senza essere notato."}
    ],
    "Pellegrino": [
        {"name": "Rifugio del Fedele", "desc": "Puoi trovare rifugio gratuito e pasti in templi e santuari della tua fede."}
    ],
    "Soldato": [
        {"name": "Grado Militare", "desc": "Il tuo rango militare è riconosciuto. I soldati leali a questa gerarchia ti riconoscono e ti prestano obbedienza."}
    ],
    "Spia": [
        {"name": "Contatto Criminale", "desc": "Hai un contatto affidabile che funge da collegamento con la tua rete di informatori e agenti."}
    ],
    "Viveur": [
        {"name": "Ospite Senza Rivali", "desc": "In cambio della tua compagnia, puoi sempre trovare un luogo dove stare e un pasto caldo nelle case aristocratiche."}
    ],
}
